//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aMUX.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aMUX.Languages.LangsRes", typeof(LangsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aMUX.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string btnAddComment {
            get {
                return ResourceManager.GetString("btnAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string btnAddPhoto {
            get {
                return ResourceManager.GetString("btnAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address!.
        /// </summary>
        public static string btnConfMailFAIL {
            get {
                return ResourceManager.GetString("btnConfMailFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s begin!.
        /// </summary>
        public static string btnConfMailOK {
            get {
                return ResourceManager.GetString("btnConfMailOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string btnCong {
            get {
                return ResourceManager.GetString("btnCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake.
        /// </summary>
        public static string btnRetake {
            get {
                return ResourceManager.GetString("btnRetake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About aMUX.
        /// </summary>
        public static string lblAboPage {
            get {
                return ResourceManager.GetString("lblAboPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment below:.
        /// </summary>
        public static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom comment:.
        /// </summary>
        public static string lblCommentPrev {
            get {
                return ResourceManager.GetString("lblCommentPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address:.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera scan.
        /// </summary>
        public static string lblOperaPage {
            get {
                return ResourceManager.GetString("lblOperaPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera preview:.
        /// </summary>
        public static string lblOperaPrev {
            get {
                return ResourceManager.GetString("lblOperaPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom photo:.
        /// </summary>
        public static string lblPhotoPrev {
            get {
                return ResourceManager.GetString("lblPhotoPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point a QR code to scan.
        /// </summary>
        public static string lblQRScan {
            get {
                return ResourceManager.GetString("lblQRScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah, sorry, feature not implemented..
        /// </summary>
        public static string msgNotImpl {
            get {
                return ResourceManager.GetString("msgNotImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the opera.
        /// </summary>
        public static string pvtData {
            get {
                return ResourceManager.GetString("pvtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string pvtPic {
            get {
                return ResourceManager.GetString("pvtPic", resourceCulture);
            }
        }
    }
}
